"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export function LoginForm(){
  const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [showPassword,setShowPassword]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const email=String(f.get("email"));const password=String(f.get("password"));const supabase=createClient();if(!supabase){setError("Supabase belum dikonfigurasi. Pastikan kamu sudah mengisi URL dan Key di file .env.local!");setBusy(false);return;}const {data,error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError){setError(authError.message);setBusy(false);return;}const {data:profile}=await supabase.from("profiles").select("role").eq("id",data.user.id).single();router.push(profile?.role==="client"?"/portal":"/dashboard");router.refresh();}
  return <form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-[10px] font-semibold text-[#5d7189]">Email<div className="mt-2 flex h-11 items-center gap-2 rounded-md border border-[#dfe6ee] px-3"><Mail size={14} className="text-[#8b9aaf]"/><input name="email" required type="email" placeholder="you@email.com" className="w-full text-xs outline-none"/></div></label><label className="block text-[10px] font-semibold text-[#5d7189]">Password<div className="mt-2 flex h-11 items-center gap-2 rounded-md border border-[#dfe6ee] px-3"><LockKeyhole size={14} className="text-[#8b9aaf]"/><input name="password" required type={showPassword?"text":"password"} placeholder="••••••••" className="w-full text-xs outline-none"/><button type="button" onClick={()=>setShowPassword(!showPassword)} className="text-[#8b9aaf] hover:text-[#5d7189]">{showPassword?<EyeOff size={14}/>:<Eye size={14}/>}</button></div></label><div className="text-right"><button type="button" className="text-[10px] font-medium text-[#2f80ed]">Forgot password?</button></div>{error&&<p className="rounded-md bg-[#fff2f3] p-2.5 text-[10px] text-[#bd5964]">{error}</p>}<button disabled={busy} className="flex h-11 w-full items-center justify-center rounded-md bg-[#173b58] text-xs font-semibold text-white disabled:opacity-60">{busy?"Signing in...":"Login"}</button></form>
}
